/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify */

#ifndef _Included_com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify
#define _Included_com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify
#ifdef __cplusplus
extern "C" {
#endif
#undef com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify_MAX_STROKE
#define com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify_MAX_STROKE 31L
/*
 * Class:     com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify
 * Method:    nativeStrokeNumber
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_axen_launcher_wp7_ui_apputil_TranditionalChineseClassify_nativeStrokeNumber
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
